---
# handlers file for basic
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start v2ray
  service:
    name: v2ray
    state: started
    enabled: yes

- name: restart v2ray
  service:
    name: v2ray
    state: restarted
