---
# - name: Add Nginx PPA
#   apt_repository:
#     repo: "{{ item }}"
#     state: present
#   with_items:
#     - ppa:nginx/stable
#     - ppa:ondrej/php


- name: Remove Apache
  apt:
    name: apache2
    state: absent
    purge: yes


- name: Install Nginx and PHP
  apt:
    name: '{{ packages.split() }}'
    state: present
    update_cache: yes
  vars:
    packages: >
      nginx libnginx-mod-http-fancyindex
      php-fpm php-mysql php-curl
      php-mbstring php-gd php-xml
  notify: start nginx
