---
# handlers file for nginx
- name: start nginx
  service:
    name: nginx
    state: started

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart php-fpm
  service:
    name: "php{{ php_version }}-fpm"
    state: restarted

- name: start php-fpm
  service:
    name: "php{{ php_version }}-fpm"
    state: started
